# Generated by Django 4.0 on 2022-01-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
                ('URLimagen', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cremas',
        ),
        migrations.DeleteModel(
            name='Labiales',
        ),
    ]
